### ISSUE TITLE
接口404

### ISSUE THREAD

**Issue by streakyPorker** [leafcoder/django-covid19#12]
为什么所有和cities有关的接口都变404了，是接口变动了么

**Comment by leafcoder** [comment]
谢谢提醒，接口现在和最开始比有所变更，但文档未做对应更新，城市接口均需加上国家编码：

暂时只支持国内城市，接口如下如：
http://111.231.75.86:8000/api/cities/CHN/
http://111.231.75.86:8000/api/cities/CHN/大庆/
http://111.231.75.86:8000/api/cities/CHN/深圳/
