### ISSUE TITLE
大佬你好，我HTML不太好，在修改你的演示时文件时遇到了问题来请教一下

### ISSUE THREAD

**Issue by Kingstom8MB** [leafcoder/django-covid19#17]
是这样的，我最近在做一个疫情分析的程序只要显示中国的情况。在git上看到你演示的布局挺不错的，就想把你的演示HTML文档加到我的ui界面里。我对HTML文档进行了一些删改，想让它只显示中国的数据。而在移动地图时我发现我不知道怎么移动地图的位置和改变地图边框的宽和高，请问你可不可以告诉我一下怎么修改它，谢谢。如果你的演示不能被这样使用的话我在此表示歉意，并会将其从我的程序里删除。
我想让地图显示在屏幕中央，并且范围大一些，一次显示全所有的省份。
他现在给我改成了这样：
![image](https://user-images.githubusercontent.com/50566074/102213719-1d643600-3f12-11eb-9cbc-1a9c028b0b1c.png)

**Comment by leafcoder** [comment]
整体的布局是使用的 flex 布局，建议 Google 了解一下 flex 布局，简单说就是更改 flex 值后，页面整体会根据 flex 值自动调整页面布局：
![image](https://user-images.githubusercontent.com/1251277/102310177-7204c100-3fa5-11eb-8e62-7bc390418106.png)

从你上传的图来看，其实，你可以配置一个左边为 flex: 1，右边部分 flex: 3，这样，整体页面宽度会平均分成 4 份，左边占1/4，右边占 3/4。内部的图表会根据容器本身的大小进行宽高自适应。

**Comment by Kingstom8MB** [comment]
非常感谢解答，调了之后，显示出了我想要的效果，谢谢。
![image](https://user-images.githubusercontent.com/50566074/102324392-c2d3e400-3fbc-11eb-9e58-a391d65d6654.png)
