### ISSUE TITLE
请问网站接口访问不了了

### ISSUE THREAD

**Issue by ghost** [leafcoder/django-covid19#37]
报错 ERR_CONNECTION_REFUSED 这个是api接口

**Comment by leafcoder** [comment]
已重启。

**Comment by ghost** [comment]
不会再关了吧，大神可以挺到6月结束吗，您的接口对我很重要，拜托了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月4日(周一) 晚上9:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leafcoder/django-covid19] 请问网站接口访问不了了 (Issue #37)




 
已重启。

**Comment by leafcoder** [comment]
> 不会再关了吧，大神可以挺到6月结束吗，您的接口对我很重要，拜托了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月4日(周一) 晚上9:17 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [leafcoder/django-covid19] 请问网站接口访问不了了 (Issue #37) 已重启。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的。

**Comment by ghost** [comment]
谢谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leafcoder/django-covid19] 请问网站接口访问不了了 (Issue #37)




  
不会再关了吧，大神可以挺到6月结束吗，您的接口对我很重要，拜托了。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年4月4日(周一) 晚上9:17 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [leafcoder/django-covid19] 请问网站接口访问不了了 (Issue #37) 已重启。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
好的。

**Comment by ghost** [comment]
大神，接口又不能访问了，网站也全部乱掉了，麻烦您看一下，我很需要您的接口，马上要交毕业设计答辩了，拜托您帮帮我，救急。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leafcoder/django-covid19] 请问网站接口访问不了了 (Issue #37)




  
不会再关了吧，大神可以挺到6月结束吗，您的接口对我很重要，拜托了。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年4月4日(周一) 晚上9:17 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [leafcoder/django-covid19] 请问网站接口访问不了了 (Issue #37) 已重启。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
好的。

**Comment by ghost** [comment]
可以加您联系方式吗，方便我请教你，QQ微信都可以
