### ISSUE TITLE
请问可以获取 某个国家各个州或省的历史数据吗？

### ISSUE THREAD

**Issue by ccjhpu** [leafcoder/django-covid19#8]
你好，请问可以获取 某个国家各个州或省的历史数据吗，比如美国每个州从疫情爆发到截止目前每天的数据吗？麻烦了

**Comment by leafcoder** [comment]
抱歉，当前项目中国家以下某省（某州）数据仅包含中国相关数据。

由于数据源来自丁香园（http://ncov.dxy.cn），且丁香园中并未维护除中国外其他国家某省某州的数据，所以本项目暂未提供这方面的数据。

后续可以调研一下国际数据比较完善的数据源，再将其纳入本项目中。

**Comment by ccjhpu** [comment]
好的，我刚找到一个统计美国各州的数据api，提供给您参考：https://aistudio.baidu.com/aistudio/projectdetail/333664

**Comment by leafcoder** [comment]
感谢，我会尽快安排时间处理下。

**Comment by ccjhpu** [comment]
https://coronavirus.1point3acres.com/zh/world，你好，这个链接的下面有每个国家的州的汇总数据，但还是没有每天的历史数据，希望能帮到一点吧

**Comment by leafcoder** [comment]
好的，我会根据数据源的实际情况做一定的处理，不过 [https://coronavirus.1point3acres.com/zh/world](https://coronavirus.1point3acres.com/zh/world) 应该会延后处理。

另外，美国各州的数据（汇总、每天）正在以 [covidtracking](https://covidtracking.com/data) 作为数据源进行处理，我会将尽量将数据结构调整为 [丁香园](http://ncov.dxy.cn/ncovh5/view/pneumonia) 的方式，不过由于各个数据源间统计方式的不同，数据精确度并不能有所保证，所以也会将原始数据提供出来，以供选择，接口应该会在近期的下个版本 v0.4a0 中尝试发布出来。

**Comment by ccjhpu** [comment]
好的，这个开源项目也有很多有用数据：https://github.com/CSSEGISandData/COVID-19
希望看到的朋友可以一起帮忙哈

**Comment by leafcoder** [comment]
> 好的，我刚找到一个统计美国各州的数据api，提供给您参考：https://aistudio.baidu.com/aistudio/projectdetail/333664

请见 [版本v0.4a0](https://github.com/leafcoder/django-covid19/releases/tag/v0.4a0)，文档与接口均已更新。

**Comment by ccjhpu** [comment]
> > 好的，我刚找到一个统计美国各州的数据api，提供给您参考：https://aistudio.baidu.com/aistudio/projectdetail/333664
> 
> 请见 [版本v0.4a0](https://github.com/leafcoder/django-covid19/releases/tag/v0.4a0)，文档与接口均已更新。

您好，可以把某州日统计的接口调整为如果不传州的简称参数的话，默认返回全部州的日统计数据呢，还有就是API页面（http://ncov.leafcoder.cn/docs/#/?id=state）下面无法登陆进行评论。

**Comment by leafcoder** [comment]
> > > 好的，我刚找到一个统计美国各州的数据api，提供给您参考：https://aistudio.baidu.com/aistudio/projectdetail/333664
> 
> > 
> 
> > 请见 [版本v0.4a0](https://github.com/leafcoder/django-covid19/releases/tag/v0.4a0)，文档与接口均已更新。
> 
> 
> 
> 您好，可以把某州日统计的接口调整为如果不传州的简称参数的话，默认返回全部州的日统计数据呢，还有就是API页面（http://ncov.leafcoder.cn/docs/#/?id=state）下面无法登陆进行评论。

谢谢，文档评论的问题已经解决。

另外，现有接口是把 /api/states/USA/ 接口作为返回当前美国各州最新疫情情况的，跟其他接口模式一致。

如果需要直接返回美国各州日统计，我可以新增一个接口类似 /api/states/USA/daily/，返回内容格式为：

按照州 state 缩写、日期进行结果排序；

```
[
    // A州日统计
    {
        A州x日统计
    },
    {
        A州y日统计
    },
    ...
    // B州日统计
    {
        B州x日统计
    },
    {
        B州y日统计
    },
    ...
]
```

**Comment by ccjhpu** [comment]
你好，可以在全球疫情里加一个包括中国在内的 每个国家每日的统计，
在各国各州里面加一个中国各省份每日的统计接口吗？麻烦了

**Comment by leafcoder** [comment]
> 你好，可以在全球疫情里加一个包括中国在内的 每个国家每日的统计，
> 在各国各州里面加一个中国各省份每日的统计接口吗？麻烦了
> 
> 我找到了这个数据，供您参考：
> https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv
> https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json

新增一个全球各国每日统计的接口是可行的，初步估计会加到接口 /api/countries/daily/ 上。

各国各州里面加入中国各省份的数据不太合适，主要是 state 本身是带有主权国家的含义，把国内省份数据放到这个接口下面会有些不方便。
可行的方式是放到 /api/provinces/USA/daily/ /api/provinces/CN/daily/ 这类的接口中；不过这样的话，其实 /api/states/??? 这类接口就没必要了，直接用 /api/provinces/??? 来做替换。

**Comment by ccjhpu** [comment]
> > 你好，可以在全球疫情里加一个包括中国在内的 每个国家每日的统计，
> > 在各国各州里面加一个中国各省份每日的统计接口吗？麻烦了
> > 我找到了这个数据，供您参考：
> > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv
> > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json
> 
> 新增一个全球各国每日统计的接口是可行的，初步估计会加到接口 /api/countries/daily/ 上。
> 
> 各国各州里面加入中国各省份的数据不太合适，主要是 state 本身是带有主权国家的含义，把国内省份数据放到这个接口下面会有些不方便。
> 可行的方式是放到 /api/provinces/USA/daily/ /api/provinces/CN/daily/ 这类的接口中；不过这样的话，其实 /api/states/??? 这类接口就没必要了，直接用 /api/provinces/??? 来做替换。

我的意思是加一个中国各省份的日统计历史数据，就是类似api/provinces/CN/daily/ 这样的。

**Comment by leafcoder** [comment]
> > > 你好，可以在全球疫情里加一个包括中国在内的 每个国家每日的统计，
> 
> > > 在各国各州里面加一个中国各省份每日的统计接口吗？麻烦了
> 
> > > 我找到了这个数据，供您参考：
> 
> > > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv
> 
> > > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json
> 
> > 
> 
> > 新增一个全球各国每日统计的接口是可行的，初步估计会加到接口 /api/countries/daily/ 上。
> 
> > 
> 
> > 各国各州里面加入中国各省份的数据不太合适，主要是 state 本身是带有主权国家的含义，把国内省份数据放到这个接口下面会有些不方便。
> 
> > 可行的方式是放到 /api/provinces/USA/daily/ /api/provinces/CN/daily/ 这类的接口中；不过这样的话，其实 /api/states/??? 这类接口就没必要了，直接用 /api/provinces/??? 来做替换。
> 
> 
> 
> 我的意思是加一个中国各省份的日统计历史数据，就是类似api/provinces/CN/daily/ 这样的。

明白了，我会把现有数据结构调整一下先。

**Comment by leafcoder** [comment]
> > > 你好，可以在全球疫情里加一个包括中国在内的 每个国家每日的统计，
> 
> > > 在各国各州里面加一个中国各省份每日的统计接口吗？麻烦了
> 
> > > 我找到了这个数据，供您参考：
> 
> > > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv
> 
> > > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json
> 
> > 
> 
> > 新增一个全球各国每日统计的接口是可行的，初步估计会加到接口 /api/countries/daily/ 上。
> 
> > 
> 
> > 各国各州里面加入中国各省份的数据不太合适，主要是 state 本身是带有主权国家的含义，把国内省份数据放到这个接口下面会有些不方便。
> 
> > 可行的方式是放到 /api/provinces/USA/daily/ /api/provinces/CN/daily/ 这类的接口中；不过这样的话，其实 /api/states/??? 这类接口就没必要了，直接用 /api/provinces/??? 来做替换。
> 
> 
> 
> 我的意思是加一个中国各省份的日统计历史数据，就是类似api/provinces/CN/daily/ 这样的。

明白了，我会把现有数据结构调整一下先。

**Comment by leafcoder** [comment]
> > > 你好，可以在全球疫情里加一个包括中国在内的 每个国家每日的统计，
> > > 在各国各州里面加一个中国各省份每日的统计接口吗？麻烦了
> > > 我找到了这个数据，供您参考：
> > > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv
> > > https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json
> > 
> > 
> > 新增一个全球各国每日统计的接口是可行的，初步估计会加到接口 /api/countries/daily/ 上。
> > 各国各州里面加入中国各省份的数据不太合适，主要是 state 本身是带有主权国家的含义，把国内省份数据放到这个接口下面会有些不方便。
> > 可行的方式是放到 /api/provinces/USA/daily/ /api/provinces/CN/daily/ 这类的接口中；不过这样的话，其实 /api/states/??? 这类接口就没必要了，直接用 /api/provinces/??? 来做替换。
> 
> 我的意思是加一个中国各省份的日统计历史数据，就是类似api/provinces/CN/daily/ 这样的。

已更新，加入接口美国所有州日统计、中国所有省份日统计。接口有所调整，具体见文档。
